### ISSUE TITLE
Static cache not invalidated after editing content via CP

### ISSUE THREAD

**Issue by wesort** [statamic/v2-hub#1026]
### Expected behaviour

A user edits content of any kind via the Control Panel > They save the changes > Visitors to the site _should_ get the freshest content
### Actual behaviour

The changes are not seen (static pages aren't being invalidated) 
### Steps to reproduce
1.  Static caching: https://docs.statamic.com/caching#full-measure
   1.1 Turned on 
   1.2 With type = File
   1.3 Uncommented the following from .htaccess

```
RewriteCond %{REQUEST_FILENAME}   !-f
RewriteCond %{REQUEST_METHOD} GET
RewriteRule ^(.*) static/$1/index.html
```

-2.  User changes some content in the Control panel and saves changes
-3.  User tests live URL (even via incognito, with a hard refresh or another device) and the content has not changed
-4. **NB:** Running `php please clear:static` will provide the new content 
### Server configuration

**Operating system**: Linux
**Web server:** Apache
**PHP version:** 5.6
**Statamic version:** 2.1.14
**Updated from an older Statamic or fresh install:** Fresh
**List of installed addons:** None

**Comment by jackmcdade** [comment]
If you scroll down that page just a tiny bit more until you get to **Invalidation** -- did you set up those rules?

**Comment by wesort** [comment]
I was using full measure and I read the docs as meaning there was nothing to be set further. Ideally, any pages or entries that are saved will invalidate the previous version.

**Comment by jackmcdade** [comment]
Right, but if you're looking at a blog-listing page for example, Statamic doesn't know to pop that cache until you tell it.

**Comment by wesort** [comment]
So can I give Statamic a global rule to invalidate on all saved changes (pages or entries)? Or do I need to specify each collection and page?

**Comment by jasonvarga** [comment]
The page itself should be invalidated automatically. If it's not, this might be a bug.

- If you edit /blog/my-post - then /blog/my-post should get invalidated.
- If you want /blog (which might display content from /blog/my-post) to be invalidated, you have to set up a rule for that.

**Comment by wesort** [comment]
I think it might be a bug then as the individual pages aren't getting invalidated.

Should I create a branch of the site and share it with you?

As a feature request, I'd like to see a way to invalidate any dependent pages (ie: /blog) if child pages (ie: /blog/my-post) are updated. Going back to my original point: invalidation kicks in when changes are saved. Static caching is powerful from a performance perspective, but the setup as it stands isn't intuitive to me.

**Comment by jasonvarga** [comment]
You say:

> I think it might be a bug then as the individual pages aren't getting invalidated.

then you say: 

> Going back to my original point: invalidation kicks in when changes are saved. 

Am I misunderstanding something? Looks like you said "it doesn't work" then "it does work".

**Comment by jackmcdade** [comment]
What i'm saying though is because you can build your site _any way you want_, with any routes and URLs you want, it's not always possible for us to know what needs to be popped.

**Comment by wesort** [comment]
@jasonvarga - Sorry, missed out the _should_ in my haste. It's not working and have turned it off on the live site.

I understand and appreciate the power and flexibility the rules give. However, I want all changes in the control panel to be reflected in the live site. Creating specific / custom routes and rules when ALL are applicable doesn't feel DRY. Obviously, I am ignorant to _how_ the invalidation functions from Statamic's perspective and get that the static cache needs informing that it's out of date.

**Comment by jackmcdade** [comment]
If *all* URLs potentially need to be invalidated, just do a `*` and move on. :)

**Comment by wesort** [comment]
Awesome. That's what I'm after!

So how exactly would I enter the `*` though? Like this?
```
static_caching_invalidation:
  urls: *
```

**Comment by jasonvarga** [comment]
Right now there's no "just invalidate everything all the time"

You'll need to do it just like the example from the docs, except the only url would be `*`. You'll need to do it for each collection.

**Comment by wesort** [comment]
Sorry, but I need this spelled out as what I've tested isn't working. Possibly operator error...

I have 1# collection "Projects" and these are routed to not include "projects" in the URL. This doesn't invalidate:
```
static_caching_invalidation:
  collections:
    projects:
      urls:
        - *
        - /
```

**Comment by wesort** [comment]
@jackmcdade or @jasonvarga  - Could you please show me exactly how to use the `*` wildcard url? I'm stuck and I'm still not sure if this is a bug or operator error (more likely). 

Thanks.

**Comment by brianyuen** [comment]
@wesort Was this ever resolved? I'm having a similar issue, but the site I'm developing does not have any collections. The file cache isn't invalidating after the content has been updated.

**Comment by wesort** [comment]
Nope, I don't believe it was resolved.

**Comment by jasonbell** [comment]
I’m definitely still experiencing this issue. The only invalidation rule that seems to work is clearing out the main index. I don’t see any action ont eh wildcard rules setup, and the individual piece of content—page or collection—does not invalidate when updated via CP.

### Expected behaviour
Tell us what you assumed would happen, as optimistically as possible.  
If it's just "it should work", you can remove this section.

Enabled full measure, file based static cache. Load front page and a secondary page to prime the cache. Sign in and edit a collection item and expect `/static/index.html` and `/static/collection-item-path/index.html` to be removed.

### Actual behaviour
Cache files are not being removed.

### Steps to reproduce
1.  Configure caching. Example…
```
stache_always_update: false
static_caching_enabled: true
static_caching_type: file
static_caching_ignore_query_strings: true
static_caching_invalidation:
  collections:
    tiles:
      urls:
        - /
        - /tiles/*
  pages:
    urls:
      - /contacts
```
2.  Visit `/contacts` and `/tiles/some-page/` and `/`
3.  Verify that static cache has been built for these items
4. Edit `/tiles/some-page` via CP and save.
5. Cache file for `/` is gone. Cache file for `/tiles/some-page/index.html` has not been removed. Reload `/tiles/some-page` and find changes not visible.
6. Repeat 3-5 for `/contacts` and find same result.

### Server configuration
**Operating system**:
CENTOS 7.3

**Web server:**
Apache/2.4.16

**PHP version:**
PHP 5.6.14

**Statamic version:**
2.1.19

**Updated from an older Statamic or fresh install:**
Updated

**List of installed addons:**
none

**Comment by wesort** [comment]
FWIW, I'm happy to have this issue closed. I won't close it though as others have experienced it.

**Comment by jackmcdade** [comment]
This issue has been inactive and in need of more information for a while now. Feel free to reopen and we'd be more than happy to take another look if you have more info that can help!
