### ISSUE TITLE
URGENT {{ paginate:auto_links }} broken in Statamic 2.6.3

### ISSUE THREAD

**Issue by dorra** [statamic/v2-hub#1549]
### Expected behaviour
{{ paginate:auto_links }} should create links for each page like
`<a href="http://www.site.com/blog?page=6">6</a>`

### Actual behaviour
It creates broken parameter strings like:
`<a href="http://www.site.com/blog?page=2%3Fpage%3D3?page=6">6</a>`

### Steps to reproduce
1.  Create a collection template with `{{ paginate:auto_links }}`
2.  Click on Page Link 2,3,4,5,6
3.  Links do not work correctly, you get always page 2

### Server Details

**Operating System**: Ubuntu

**Web Server:** Apache

**PHP Version:** 7.1

**Statamic Version:** 2.6.3

**Updated from an older Statamic or fresh install:** update

**List of installed addons:** none

**Comment by rrelmy** [comment]
This should fix the issue 
``` patch
Index: statamic/bundles/Collection/CollectionTags.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- statamic/bundles/Collection/CollectionTags.php	(date 1502631999000)
+++ statamic/bundles/Collection/CollectionTags.php	(revision )
@@ -500,7 +500,7 @@
 
         $paginator = new LengthAwarePaginator($items, $count, $this->limit, $page);
 
-        $paginator->setPath(request()->getUri());
+        $paginator->setPath(request()->path());
         $paginator->appends(Request::all());
 
         $this->pagination_data = [

```

**Comment by dorra** [comment]
This fix worked. Thanks a lot!

**Comment by dorra** [comment]
Ops. Still a Problem wrong taxonomy urls: http://www.site.com/blog/category/blog/category/marketing?page=3

**Comment by rrelmy** [comment]
I updated the patch above to use `->url()` instead of `->path()`.
