### ISSUE TITLE
v2.11.1 - Replicator field labels not displaying on fieldset editor

### ISSUE THREAD

**Issue by pjhartin** [statamic/v2-hub#2235]
**Describe the bug**
Since updating to 2.11.1 all replicator fields in the CMS are not displaying their labels.
From investigating the markup, we can see that the content is there, however, the width of the `field-display` label is 0px.

Looking deeper into the Vue components (using VueTools chrome extension), we can see that the `nameFieldWidth` data property on the `FieldsetField` component is also set to "0". If we update this using VueTools to "50px" as an example, the width updates accordingly. 

It seems that the widths are not being calculated in the component properly and so all the labels are essentially hidden which results in the following:

![image](https://user-images.githubusercontent.com/1385026/48100087-0607e880-e276-11e8-89ec-4bb0aaf0a46f.png)

> Note, the last fieldset in the above screenshot ("field_9") is a field that has just been added during the current instance, which shows that the width is being calculated correctly for new fieldsets. However, upon a page refresh, this will look like the others and have no width.

**To Reproduce**
1. Update Statamic to latest
2. Look at existing replicators and their field labels

**Expected behavior**
To be able to see the labels.

**Environment details (please complete the following information):**
 - Statamic Version: 2.11.1
 - Fresh Install or Upgrade: Upgrade
 - OS: MacOS 10.14.1 (18B75)
 - Browser: Chrome and Safari (havent tested any others)
 - Web Server: Apache, Nginx and Valet (on production and locally)
 - PHP Version: 7.1
 - Addons installed: N/A

**Comment by pjhartin** [comment]
As a workaround for now we are using 
```
/* Custom Control Panel styles... */
input.field-name {
  width: auto !important;
}
input.field-display {
  width: auto !important;
}
```
in `overrides.css` so that we can continue using the editor views.

**Comment by jackmcdade** [comment]
This was fixed in 2.11.1 though. Can you hard-refresh to make sure you don't have any css/js cached in your browser?

**Comment by pjhartin** [comment]
I just double checked and it's all the same.
No JS/CSS cached here. 
I just updated to 2.11.2 to test, and it's the same there too.

Tested on various machines in our team, including those that have never seen a statamic site.

**Comment by Boolian** [comment]
Still not fixed.... seems javascript control's the width of the input when you create the fields but then doesn't resize them when loading the page after the fact

**Comment by jasonvarga** [comment]
I can't replicate (ha.) this.

Can you provide some more details? What browser? Statamic version? Post the whole fieldset?

**Comment by jasonvarga** [comment]
Actually, I just fixed #2372 which I suspect is the same issue.

See if 2.11.11 helps once it's out.
