### ISSUE TITLE
Updater inaccurately displayed

### ISSUE THREAD

**Issue by wesort** [statamic/v2-hub#938]
### Expected behaviour

Statamic icon in Control Panel only shows "Update Available" when not running on latest release. This is directly after updating and hard refreshing the page.
### Actual behaviour

On latest release, "Update Available" appears next to Statamic badge (top left of CP)

![inaccurate-updater](https://cloud.githubusercontent.com/assets/3920126/18358226/075f15e4-75ec-11e6-9abe-4e735af3292f.png)
### Server configuration

**Operating system**:
Linux
**Web server:**
Apache
**PHP version:**
5.6
**Statamic version:**
2.1.7
**Updated from an older Statamic or fresh install:**

**List of installed addons:**
N/A

**Comment by wesort** [comment]
Suddenly this is resolved??

**Comment by wesort** [comment]
I'm afraid this has returned for me. Have refreshed and hard-refreshed my browser but message is still there.

Same as above but now:
PHP 7.0
Statamic 2.1.19 (latest release)

![update msg inaccurate](https://cloud.githubusercontent.com/assets/3920126/22103848/a08fff8e-de34-11e6-9e5e-52cad0aae08e.png)

**Comment by jackmcdade** [comment]
I don't believe this is still an issue. Please reopen if you have evidence otherwise!

**Comment by wesort** [comment]
I hate reporting this but the issue was still present for a least 15 minutes after updating.

![update-notification-is-lying](https://cloud.githubusercontent.com/assets/3920126/22544897/9da2f236-e92e-11e6-8eaa-7329cae00f53.png)

It has now gone though and I suspect that could be because I saved a few pages and settings AFTER taking the screenshot above. Perhaps that caused a cache to clear or maybe something else is going on??

**Comment by wesort** [comment]
Update: In updating another site I found the notification issue was being shown incorrectly AFTER updating to latest. Saving a page changed nothing, but saving a setting did remove the issue. I presume a cache was cleared.

Perhaps clearing that cache should be adding the updater's process?
